/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "VERT.h"
#include "VGA_aliases.h"
#include "VGA.h"
#include "HORIZ.h"
#include "DMA_dma.h"
#include "VGA_CLK.h"
#include "NEWLINE.h"
#include "VSYNC.h"
#include "HSYNC.h"
#include "PIXEL.h"
#include "ADC_SAR_1.h"
#include "HSYNC_OUT_aliases.h"
#include "HSYNC_OUT.h"
#include "VSYNC_OUT_aliases.h"
#include "VSYNC_OUT.h"
#include "ADC_SAR_2.h"
#include "VRx_aliases.h"
#include "VRx.h"
#include "VRy_aliases.h"
#include "VRy.h"
#include "UART.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "ADC_SAR_2_IRQ.h"
#include "ADC_SAR_2_theACLK.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

